name: Automatic Dataset Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_preprocessing_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository (Fetch full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow matplotlib dagshub

      - name: Run Preprocessing Script
        run: |
          echo "Running automate_SabrinaYusrina.py..."
          python preprocessing/automate_SabrinaYusrina.py

      - name: Run Modelling and Log to DagsHub
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python Membangun_model/modelling_tuning.py --data_path preprocessing/laptop_clean.csv

      - name: Commit and Push Updated Dataset
        uses: EndBug/add-and-commit@v9
        with:
          add: "preprocessing/laptop_clean.csv"
          message: "chore(data): Update preprocessed dataset via GitHub Action run (Final Fix)"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          default_author: github_actions
